steps:

- id: "Execução dos testes unitários"
  name: 'golang'
  args: ['go', 'test', './...']

- id: "Build da imagem Docker"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-hpa', '.']

- id: "Push da imagem Docker"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/go-hpa']
